version: '3.8'

services:
    mysql:
        image: mysql:latest
        container_name: ${DOCKER_PROJECT_NAME}-mysql
        environment:
            TZ: ${TIMEZONE}
            MYSQL_ROOT_PASSWORD: ${DOCKER_PROJECT_NAME}
            MYSQL_DATABASE: ${DOCKER_PROJECT_NAME}
            MYSQL_USER: ${DOCKER_PROJECT_NAME}
            MYSQL_PASSWORD: ${DOCKER_PROJECT_NAME}
        ports:
            - ${DOCKER_MYSQL_PORT}:3306
        volumes:
            - ./.db:/var/lib/mysql
        networks:
            - main

    nginx:
        image: nginx:latest
        container_name: ${DOCKER_PROJECT_NAME}-nginx
        ports:
            - ${DOCKER_NGINX_PORT}:80
            - ${DOCKER_NGINX_SSL_PORT}:443
        volumes:
            - ./.build/nginx/conf.d:/etc/nginx/conf.d
            - ./:/var/www
        networks:
            - main
        links:
            - php

    php:
        build:
            context: .
            dockerfile: .build/Dockerfile
            target: develop
            args:
                TIMEZONE: ${TIMEZONE}
        environment:
            TIMEZONE: ${TIMEZONE}
            XDEBUG_CONFIG: "idekey=${DOCKER_XDEBUG_IDEKEY}"
            PHP_IDE_CONFIG: "serverName=_"
            XDEBUG_REMOTE_HOST: ${DOCKER_XDEBUG_REMOTE_HOST}
            XDEBUG_REMOTE_PORT: ${DOCKER_XDEBUG_REMOTE_PORT}
            XDEBUG_IDEKEY: ${DOCKER_XDEBUG_IDEKEY}
        networks:
            - main
        depends_on:
            - mysql
        volumes:
            - ./:/var/www

networks:
    main:
